version: '3.7'

services:
  voila:
    container_name: voila-with_msal-template
    image: voila-with_msal-template
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: always
    volumes:
      - ../share/jupyter/voila/templates:/root/.local/share/jupyter/voila/templates
      - ../example-notebooks:/home/voila/example-notebooks
    ports:
      - 8866:8866
    command: "pipenv run voila --template with_msal example-notebooks"
