name: voici
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-javascript
  - xeus-python
  - pandas
  - bqplot
  - micropip
  # frontend components
  - ipywidgets
  - ipywebrtc
  - npm
  # - npm:
  #     - "@azure/msal-node@^2"
  #     - "@azure/msal-common"
  #     - jsonwebtoken                 # pulled in anyway, but explicit is fine
