name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install mamba
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.5.8-0'
          environment-file: 'build-environment.yml'

      - name: Build the JupyterLite site
        shell: bash -l {0}
        env:
          # Ensure nbconvert/voici can discover templates in the repository
          JUPYTER_PATH: ${{ github.workspace }}:${{ env.JUPYTER_PATH }}
        run: |
          set -euo pipefail
          echo "Attempting build using explicit template file ./with_msal.tpl"
          if voici build --contents content --output-dir dist --apps lab --template ./with_msal.tpl; then
            echo "Built using ./with_msal.tpl"
          else
            echo "Explicit template file failed; adding workspace to JUPYTER_PATH and retrying with template name 'with_msal'"
            export JUPYTER_PATH="$PWD:${JUPYTER_PATH:-}"
            echo "JUPYTER_PATH=$JUPYTER_PATH"
            voici build --contents content --output-dir dist --apps lab --template with_msal
          fi
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
